USE middle_layer;

DROP TABLE IF EXISTS heb_shopping_list;
DROP TABLE IF EXISTS heb_shopping_list_product;
DROP TABLE IF EXISTS heb_shopping_list_coupon;
DROP TABLE IF EXISTS heb_shopping_list_freeform;
DROP TABLE IF EXISTS heb_shopping_list_recipe;

CREATE TABLE heb_shopping_list (
	SHOPPING_LIST_ID VARCHAR(40) NOT NULL,
	OWNER_ID VARCHAR(40) NOT NULL,
	LIST_NAME VARCHAR(40) NOT NULL,
	CREATION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
	LAST_MODIFIED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (SHOPPING_LIST_ID)
);

CREATE TABLE heb_shopping_list_product (
	SHOPPING_LIST_ID VARCHAR(40) NOT NULL,
	PRODUCT_ID VARCHAR(40) NOT NULL,
	NOTES VARCHAR(1000),
	QUANTITY INT UNSIGNED DEFAULT 0,
	STATUS INT UNSIGNED DEFAULT 0,
	PRIMARY KEY (SHOPPING_LIST_ID, PRODUCT_ID)
);

CREATE TABLE heb_shopping_list_coupon (
	SHOPPING_LIST_ID VARCHAR(40) NOT NULL,
	COUPON_ID VARCHAR(40) NOT NULL,
	NOTES VARCHAR(1000),
	STATUS INT UNSIGNED DEFAULT 0, 
	PRIMARY KEY (SHOPPING_LIST_ID, COUPON_ID)
);

CREATE TABLE heb_shopping_list_freeform (
	SHOPPING_LIST_ID VARCHAR(40) NOT NULL,
	FREEFORM_ID VARCHAR(40) NOT NULL,
	NOTES VARCHAR(1000),
	QUANTITY INT UNSIGNED DEFAULT 0,
	STATUS INT UNSIGNED DEFAULT 0,
	PRIMARY KEY (SHOPPING_LIST_ID, FREEFORM_ID)
);

CREATE TABLE heb_shopping_list_recipe (
	SHOPPING_LIST_ID VARCHAR(40) NOT NULL,
	RECIPE_ID VARCHAR(40) NOT NULL,
	NOTES VARCHAR(1000),
	STATUS INT UNSIGNED DEFAULT 0,
	PRIMARY KEY (SHOPPING_LIST_ID, RECIPE_ID)
);