/*
 * 
 * Initial creation of the context filters for the Api Discovery Service and related Admin Portal pieces.
 * 
 */
use middle_layer;

insert into middle_layer.ls_context_filters values('apiCollection', 'apiCollection is part of Api Discovery', 
'{\"dataItemName\":\"apiCollection\",\"filters\":[{\"name\":\"default\",\"filterMap\":[{\"jsonKey\":\"collectionId\",\"propertyName\":\"id\"},{\"jsonKey\":\"name\",\"propertyName\":\"name\"},{\"jsonKey\":\"description\",\"propertyName\":\"description\"},{\"jsonKey\":\"contactInfo\",\"propertyName\":\"contactInfo\"},{\"jsonKey\":\"serviceDescriptions\",\"propertyName\":\"serviceDescriptions\"}]},{\"name\":\"AdminPortal\",\"filterMap\":[{\"jsonKey\":\"collectionId\",\"propertyName\":\"id\"},{\"jsonKey\":\"name\",\"propertyName\":\"namee\"},{\"jsonKey\":\"description\",\"propertyName\":\"description\"},{\"jsonKey\":\"contactInfo\",\"propertyName\":\"contactInfo\"},{\"jsonKey\":\"creationDate\",\"propertyName\":\"creationDate\"},{\"jsonKey\":\"lastModifiedDate\",\"propertyName\":\"lastModifiedDate\"},{\"jsonKey\":\"serviceDescriptions\",\"propertyName\":\"serviceDescriptions\"}]}],\"creationRequiredProperties\":[\"name\"],\"restrictedProperties\":[\"collectionId\",\"creationDate\",\"lastModifiedDate\"]}', 
now(), now()) ON DUPLICATE KEY UPDATE last_modified_date=now();

insert into middle_layer.ls_context_filters values('serviceDescription', 'serviceDescription is part of Api Discovery', 
'{\"dataItemName\":\"serviceDescription\",\"filters\":[{\"name\":\"default\",\"filterMap\":[{\"jsonKey\":\"serviceDescriptionId\",\"propertyName\":\"id\"},{\"jsonKey\":\"name\",\"propertyName\":\"name\"},{\"jsonKey\":\"description\",\"propertyName\":\"description\"},{\"jsonKey\":\"labels\",\"propertyName\":\"labels\"},{\"jsonKey\":\"openApiSpecUrl\",\"propertyName\":\"openApiSpecUrl\"},{\"jsonKey\":\"documentationUrl\",\"propertyName\":\"documentationUrl\"},{\"jsonKey\":\"currentVersion\",\"propertyName\":\"currentVersion\"},{\"jsonKey\":\"serviceVersions\",\"propertyName\":\"serviceVersions\"}]},{\"name\":\"AdminPortal\",\"filterMap\":[{\"jsonKey\":\"serviceDescriptionId\",\"propertyName\":\"id\"},{\"jsonKey\":\"name\",\"propertyName\":\"name\"},{\"jsonKey\":\"description\",\"propertyName\":\"description\"},{\"jsonKey\":\"labels\",\"propertyName\":\"labels\"},{\"jsonKey\":\"openApiSpecUrl\",\"propertyName\":\"openApiSpecUrl\"},{\"jsonKey\":\"documentationUrl\",\"propertyName\":\"documentationUrl\"},{\"jsonKey\":\"currentVersion\",\"propertyName\":\"currentVersion\"},{\"jsonKey\":\"lastModifiedDate\",\"propertyName\":\"lastModifiedDate\"},{\"jsonKey\":\"serviceVersions\",\"propertyName\":\"serviceVersions\"}]}],\"creationRequiredProperties\":[\"name\"],\"restrictedProperties\":[\"serviceDescriptionId\",\"creationDate\",\"lastModifiedDate\"]}', 
now(), now()) ON DUPLICATE KEY UPDATE last_modified_date=now();


insert into middle_layer.ls_context_filters values('serviceVersion', 'serviceVersion is part of Api Discovery', 
'{\"dataItemName\":\"serviceVersion\",\"filters\":[{\"name\":\"default\",\"filterMap\":[{\"jsonKey\":\"serviceVersionId\",\"propertyName\":\"id\"},{\"jsonKey\":\"versionNumber\",\"propertyName\":\"versionNumber\"},{\"jsonKey\":\"description\",\"propertyName\":\"description\"},{\"jsonKey\":\"hostName\",\"propertyName\":\"hostName\"},{\"jsonKey\":\"basePath\",\"propertyName\":\"basePath\"},{\"jsonKey\":\"openApiSpecUrl\",\"propertyName\":\"openApiSpecUrl\"},{\"jsonKey\":\"resourcePaths\",\"propertyName\":\"resourcePaths\"}]},{\"name\":\"AdminPortal\",\"filterMap\":[{\"jsonKey\":\"serviceVersionId\",\"propertyName\":\"id\"},{\"jsonKey\":\"versionNumber\",\"propertyName\":\"versionNumber\"},{\"jsonKey\":\"description\",\"propertyName\":\"description\"},{\"jsonKey\":\"hostName\",\"propertyName\":\"hostName\"},{\"jsonKey\":\"basePath\",\"propertyName\":\"basePath\"},{\"jsonKey\":\"openApiSpecUrl\",\"propertyName\":\"openApiSpecUrl\"},{\"jsonKey\":\"creationDate\",\"propertyName\":\"creationDate\"},{\"jsonKey\":\"lastModifiedDate\",\"propertyName\":\"lastModifiedDate\"},{\"jsonKey\":\"resourcePaths\",\"propertyName\":\"resourcePaths\"}]}],\"creationRequiredProperties\":[\"versionNumber\",\"hostName\"],\"restrictedProperties\":[\"serviceVersionId\",\"creationDate\",\"lastModifiedDate\"]}', 
now(), now()) ON DUPLICATE KEY UPDATE last_modified_date=now();


insert into middle_layer.ls_context_filters values('resourcePath', 'resourcePath is part of Api Discovery', 
'{\"dataItemName\":\"resourcePath\",\"filters\":[{\"name\":\"default\",\"filterMap\":[{\"jsonKey\":\"resourcePathId\",\"propertyName\":\"id\"},{\"jsonKey\":\"name\",\"propertyName\":\"name\"},{\"jsonKey\":\"description\",\"propertyName\":\"description\"},{\"jsonKey\":\"path\",\"propertyName\":\"path\"},{\"jsonKey\":\"batchPath\",\"propertyName\":\"batchPath\"}]},{\"name\":\"AdminPortal\",\"filterMap\":[{\"jsonKey\":\"resourcePathId\",\"propertyName\":\"id\"},{\"jsonKey\":\"name\",\"propertyName\":\"name\"},{\"jsonKey\":\"description\",\"propertyName\":\"description\"},{\"jsonKey\":\"path\",\"propertyName\":\"path\"},{\"jsonKey\":\"batchPath\",\"propertyName\":\"batchPath\"},{\"jsonKey\":\"creationDate\",\"propertyName\":\"creationDate\"},{\"jsonKey\":\"lastModifiedDate\",\"propertyName\":\"lastModifiedDate\"}]}],\"creationRequiredProperties\":[\"name\",\"path\"],\"restrictedProperties\":[\"resourcePathId\",\"creationDate\",\"lastModifiedDate\"]}', 
now(), now()) ON DUPLICATE KEY UPDATE last_modified_date=now();
