USE middle_layer;

ALTER TABLE atg_product ADD COLUMN CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE atg_product ADD COLUMN LAST_MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE atg_assortment ADD COLUMN CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE atg_assortment ADD COLUMN LAST_MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE atg_store ADD COLUMN CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE atg_store ADD COLUMN LAST_MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;