USE middle_layer;
drop table if exists atg_recipe;

CREATE TABLE atg_recipe (
	RECIPE_ID VARCHAR(40),
	NAME VARCHAR(100),
	CLEAN_NAME VARCHAR(100),
	MARKETING_BUG_ID VARCHAR(40),
	EXTERNAL_RECIPE_ID VARCHAR(40),
	PREPARATION_TIME VARCHAR(40),
	COOK_TIME VARCHAR(40),
	TOTAL_TIME VARCHAR(40),
	NO_OF_SERVINGS VARCHAR(100),
	CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	LAST_MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
