USE middle_layer;

CREATE USER 'hebdb' IDENTIFIED BY '@hebdb_password@';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, REFERENCES, CREATE TEMPORARY TABLES ON middle_layer.* TO 'hebdb';
