# deployment steps:
# 1. deploy the Open API spec using:
#      gcloud service-management deploy target/openapi.yaml
# 2. the output of the above command will include something like the following:
#    Service Configuration [config_id] uploaded for service [name]
# 3. update the appengine.app.modules.shoppinglist.endpoints.config.id
#    environment property with the config_id value from step #2.
# 4. deploy the full application using "mvn appengine:deploy"
# 5. callers can generate API keys (passed as "key=API_KEY") using
#    https://console.cloud.google.com/apis/credentials

swagger: '2.0'
info:
  version: 1.0.0
  title: "HEB Liquid Sky Api Discovery Service Endpoints"
  description: "HEB Liquid Sky Api Discovery Service Endpoints"
externalDocs:
  description: Internal Confluence page
  url: https://confluence.heb.com:8443/display/ESELLING/API+Discovery+Microservice
  
host: apidiscovery-dot-${appengine.app.id}.appspot.com
# "configured" means any path not specified below gets a JSON error
# response, "all" means any path not specified below is passed through
# to the application, and the request is handled by the app

# allow cross-domain ajax requests
# see https://cloud.google.com/endpoints/docs/release-notes
x-google-endpoints:
  - name: apidiscovery-dot-${appengine.app.id}.appspot.com
    allowCors: true

schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  "/apidiscovery/v1/apicollection/{collectionId}":
    get:
      operationId: ApidiscoveryGetApiCollection
      parameters:
      - name: collectionId
        in: path
        required: true
        type: string
      - name: filter
        in: query
        required: false
        type: array
        items:
          type: string
        collectionFormat: multi
      responses:
        '200':
          description: A successful response
          schema:
            "$ref": "#/definitions/ApiCollection"
      security:
      - api_key: []
  "/echo/v1/echo":
    post:
      operationId: EchoTestEcho
      parameters:
      - in: body
        name: body
        required: false
        schema:
          "$ref": "#/definitions/JsonMap"
      responses:
        '200':
          description: A successful response
          schema:
            "$ref": "#/definitions/JsonMap"
      security:
      - api_key: []
securityDefinitions:
  api_key:
    type: apiKey
    name: key
    in: query
definitions:
  ResourcePath:
    properties:
      batchPath:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      path:
        type: string
  ServiceDescription:
    properties:
      currentVersion:
        type: string
      description:
        type: string
      documentation:
        type: string
      id:
        type: string
      labels:
        type: string
      name:
        type: string
      openApiSpecUrl:
        type: string
      serviceVersions:
        type: array
        items:
          "$ref": "#/definitions/ServiceVersion"
  ServiceVersion:
    properties:
      basePath:
        type: string
      description:
        type: string
      hostName:
        type: string
      id:
        type: string
      openApiSpecUrl:
        type: string
      resourcePaths:
        type: array
        items:
          "$ref": "#/definitions/ResourcePath"
      versionNumber:
        type: string
  ApiCollection:
    properties:
      contactInfo:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      serviceDescriptions:
        type: array
        items:
          "$ref": "#/definitions/ServiceDescription"
  JsonMap: {}
