service: taskqueue

runtime: java
env: flex

runtime_config:
   jdk: openjdk8

handlers:
- url: /.*
  script: this field is required, but ignored
  secure: always
- url: /cron/*
  script: _go_app
  login: admin

threadsafe: true

resources:
  memory_gb: ${appengine.app.modules.taskqueue.specs.memory_gb}

automatic_scaling:
  min_num_instances: ${appengine.app.modules.taskqueue.specs.min-num-instances}
  max_num_instances: ${appengine.app.modules.taskqueue.specs.max-num-instances}

health_check:
  check_interval_sec: ${appengine.app.modules.taskqueue.check_interval_sec}

beta_settings:
  # don't scan for annotations at every startup
  java_quickstart: true
