CREATE TABLE test_product (
	prod_id VARCHAR(40) NOT NULL,
	title VARCHAR(200),
	CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	LAST_MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (prod_id)
);
CREATE TABLE test_product_aux (
	prod_id VARCHAR(40) NOT NULL,
	description VARCHAR(2000),
	PRIMARY KEY (prod_id),
	FOREIGN KEY (prod_id) REFERENCES test_product(prod_id)
);
CREATE TABLE test_sku (
	sku_id VARCHAR(40) NOT NULL,
	title VARCHAR(200),
	CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	LAST_MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (sku_id)
);
CREATE TABLE test_sku_aux (
	sku_id VARCHAR(40) NOT NULL,
	description VARCHAR(2000),
	PRIMARY KEY (sku_id),
	FOREIGN KEY (sku_id) REFERENCES test_sku(sku_id)
);
CREATE TABLE test_product_sku (
	prod_id VARCHAR(40) NOT NULL,
	sku_id VARCHAR(40) NOT NULL,
	PRIMARY KEY (prod_id, sku_id),
	FOREIGN KEY (prod_id) REFERENCES test_product(prod_id),
	FOREIGN KEY (sku_id) REFERENCES test_sku(sku_id)
);
