imports:
- path: project.py

resources:
# The "name" property below will be the name of the new project
- name: heb-dm-proj-mmtest-1
  type: project.py
  properties:
    # Change this to your organization ID.
    organization-id: "315713210212"
    # Change the following to your organization's billing account
    billing-account-name: billingAccounts/00DE9B-7FDFCE-FF57EC
    # The apis to enable in the new project.
    # To see the possible APIs, use gcloud CLI: gcloud service-management list
    apis:
    - compute-component.googleapis.com
    - deploymentmanager.googleapis.com
    - pubsub.googleapis.com
    - storage-component.googleapis.com
    - monitoring.googleapis.com
    - logging.googleapis.com
    # The service accounts you want to create in the project
    service-accounts:
    - my-service-account-1
    - my-service-account-2
    # IAM policy on the new project
    iam-policy:
      bindings:
      - role: roles/owner
        members:
        # Make sure to include the DM service account that is doing the deployment!
        #- serviceAccount:218016593287@cloudservices.gserviceaccount.comm
        # Add any others you want to have access
        - user:bob.hewett@mutualmobile.com
      #- role: roles/viewer
      #  members:
      #  - user:iamtester@deployment-manager.net

